bandprotocol/cosmoscan

src/components/tx-index/IndexDataMsg.re, src/pages/DataSourceIndexPage.re, src/pages/TxIndexPage.re, src/subscriptions/DataSourceSub.re, src/utils/MsgDecoder.re
- Added `treasury` and `fee` on DataSourceIndexPage.
- Added `treasury` and `fee` on CreateDataSource and EditDataSource msg.
- Added `prepareGas` and `executeGas` on Request msg
=> add treasury, fee on data source and msg, add prepare, execute gas on request msg

src/components/tx-index/IndexIBCChannelMsg.re, src/utils/MsgDecoder.re
* Implemented mapping function
*  getStateText
*  getOrderText
* Updated the missing proof height on ChannelCloseConfirmMsg
=> IBC map the state and order

src/PacketDecoder.re, src/components/TxIndexPageTable.re, src/components/msgs/IBCPacketMsg.re, src/components/msgs/Msg.re, src/components/tx-index/IndexIBCPacketMsg.re, src/utils/MsgDecoder.re
- IBCIndexPacketMsg (Tx index page)
- IBCPacketMsg (Inline msg)
- Added new packet detail to both oracleRequest and fungible token packet type
=> IBC:  Added success and fail case to recv packet

src/components/ValidatorsTable.re, src/pages/ValidatorIndexPage.re
=> Updated voting band number

graphql_schema.json, src/components/BlockIndexTxsTable.re, src/components/TxIndexPageTable.re, src/components/ibcs/ChannelTable.re, src/components/ibcs/LiveConnection.re, src/pages/IBCHomePage.re, src/reusable/Icon.re, src/reusable/SearchInput.re, src/subscriptions/ConnectionSub.re
=> IBC: Live connection section (Bottom Part on IBCHomePage)

src/components/account/AccountIndexDelegations.re, src/components/account/AccountIndexRedelegate.re, src/components/account/AccountIndexUnbonding.re
- add staking functionality on the Account index page
- decrease page size to 5
- increase validator logo size and moniker's font size.
=> add stake functionality on account index page

src/components/ibcs/ChannelTable.re
- handle unconnected channel
- remove uppercase value
- fix wrong variable
=> Patch channels table

src/pages/DataSourceHomePage.re, src/pages/OracleScriptHomePage.re
=> remove container

src/pages/RequestIndexPage.re
https://bandprotocol.atlassian.net/jira/software/projects/DEXP/boards/13?selectedIssue=DEXP-245
- Added link to validator name
=> link validator name to its page

src/components/TxIndexPageTable.re, src/components/msgs/Msg.re, src/components/tx-index/IndexIBCTransferMsg.re, src/utils/decoders/MsgDecoder.re
=> Merge ibc transfer from main to laozi-mainnet

src/pages/ProposalIndexPage.re
=> move Vote button to be placed at the top of the page

src/components/oracle-script/OracleScriptExecuteProof.re
Change make request (proof of validity) loading component to CircleSpin with size/width of 48
=> Change make request (proof of validity) loading component

src/components/RequestFailedResult.re, src/components/RequestStatus.re, src/components/oracle-script/OracleScriptExecuteResponse.re
=> Show req message

src/components/LatestBlocks.re, src/components/block/ResolvedRequest.re, src/subscriptions/BlockSub.re
1. delete requests in some BlockSub config
2. separate BlockSub type, with requests and without requests
=> Fixed ValidatorIndex Proposed Block tab slow query

src/Index.re
- Changed the owner from Peach's to Shine's
=> :arrow_up: changed owner of sentry

README.md
Update readme for cosmoscan github page
Update command and endpoints for running development process both on testnet/mainnet
Visit README section on cosmoscan github page
=> Update cosmoscan readme

.github/workflows/cosmoscan.yml, cypress/integration/all_pages.spec.js, cypress/integration/send_action.spec.js
Github actions are broken in the step of delegations because the undelegate method has reached the limit.
Change the validator to **Band-Validator-9** and comment undelegate test case.
Run yarn integration-test
-
=> fix: scan-test error on delegation

index.html
https://bandprotocol.atlassian.net/jira/software/projects/DEXP/boards/13?selectedIssue=DEXP-402
Our team can see the website traffics and other analytics for better updates.
Remove the current GA and replace with new GTM
The report should be shown in the Google Tag Manager Dashboard
=> fix: remove ga and add gtm

index.html
[Jira](https://bandprotocol.atlassian.net/browse/DEXP-402)
Google Analytics
added gtag
- [x ] New feature (non-breaking change which adds functionality)
=> fix: add gtag

cypress/integration/send_action.spec.js
fix scan-test to have 100% pass
Remove the redelegate test case in Github workflow
Run GitHub workflow 
=> fix: remove redelegate test case

src/pages/RequestIndexPage.re
[https://bandprotocol.atlassian.net/jira/software/projects/DEXP/boards/13?selectedIssue=DEXP-431](https://bandprotocol.atlassian.net/jira/software/projects/DEXP/boards/13?selectedIssue=DEXP-431)
The `What is proof?` button is linking to the nowhere of the document
Update the link to https://docs.bandchain.org/whitepaper/terminology.html#oracle-data-proof
=> fix: update what is proof document link

src/utils/SubmitMsg.re
As the community, they couldn't reinvest on cosmoscan, the cause is about the gas limit is too low.
Increased the gas limit to 300000
=> :ambulance: increased gas limit on reinvesting

src/components/ChainIDBadge.re
[573](https://bandprotocol.atlassian.net/jira/software/projects/DEXP/boards/13?selectedIssue=DEXP-573)
Update chain dropdown
(Describe at a high level how the feature was implemented)
add testnet5 support
=> feat: add testnet5 chain dropdown

netlify.toml, vercel.json
- Add vercel.json file for the further deployment configuration
(Describe at a high level how the feature was implemented)
=> add vercel.json

src/components/oracle-script/OracleScriptExecute.re, src/contexts/AccountContext.re
Update fee to compatible with new gas price 
(Describe at a high level how the feature was implemented)
1. Go to o111
2. Try to make a request
3. It should be successful
=> :sparkles: update fee on make request

src/reusable/Markdown.re
(Describe what the feature is)
(Describe at a high level how the feature was implemented)
=> :bug: Fix the markdown style

src/components/oracle-script/OracleScriptExecute.re, src/contexts/AccountContext.re, src/pages/RequestIndexPage.re
[DEXP-859](https://bandprotocol.atlassian.net/browse/DEXP-859?atlOrigin=eyJpIjoiMjNkNTI1YzBmZmNmNDZkYjg1MDEwNjQ1NDA2YzA0NDciLCJwIjoiaiJ9)
- add gas price
- fix Tx fee digit in request page
- increase gasFee digit format from 2 to 6
- view Tx fee field in Request
[DEXP-859]: https://bandprotocol.atlassian.net/browse/DEXP-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add mainnet gas price

src/pages/RequestIndexPage.re
- fix Tx fee digit in request page
- increase gasFee digit format from 2 to 6
- view Tx fee field in Request
=> fix tx fee format digit
